services:
  account-service:
    build:
      context: ./account-service
    container_name: account-service
    depends_on:
      jaeger:
        condition: service_started
    environment:
      OTLP_TRACING_ENDPOINT: http://jaeger:4318/v1/traces
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4318:4318"

  event-gateway:
    build:
      context: ./event-gateway
    container_name: event-gateway
    depends_on:
      account-service:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      ACCOUNT_SERVICE_URL: http://account-service:8081
      OTLP_TRACING_ENDPOINT: http://jaeger:4318/v1/traces
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s